version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27016:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_mongo_username
      MONGO_INITDB_ROOT_PASSWORD: your_mongo_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - my_network

volumes:
  mongodb_data:

networks:
  my_network:
    driver: bridge
